version: '3.7'
services:
  Suma:
    container_name: sum
    image: jr/sum:latest
    build:
      dockerfile: Dockerfile
      context: ./microservices/sum
    ports:
      - '8083:8080'

  SitioWeb:
    container_name: webpage-src
    image: jr/webpage-src:latest
    build:
      dockerfile: Dockerfile
      context: ./webpage-src
    ports:
      - '8082:80'
