version: '3.7'
services:
  Suma:
    container_name: suma
    image: jr/suma:latest
    build:
      dockerfile: Dockerfile
      context: ./microservicios/suma
    ports:
      - '8090:8080'

  SitioWeb:
    container_name: sitioweb
    image: jr/sitioweb:latest
    build:
      dockerfile: Dockerfile
      context: ./webpage-src
    ports:
      - '8081:80'
